### ISSUE TITLE
FEATURE: Close the tab created in Firefox

### ISSUE THREAD

**Issue by tmknight** [clear-code/ieview-we#24]
Not sure if considered a feature or bug.  It would be preferred that when opening a flagged URL from link that generates a new tab, close the new tab that is generated.  E.g. A link is sent via email.  The URL of that link is flagged to open in IE.  Clicking the link in the email opens Firefox, or generates a new tab if FF is already open, before redirecting to IE.  The suggestion is to build logic to close the new tab (I believe that would also close FF from the first part of the previous example).

**Comment by Dimas-sc** [comment]
Interested too

**Comment by tmknight** [comment]
Closing due to to lack of response.
