### ISSUE TITLE
IEview does not work anymore

### ISSUE THREAD

**Issue by Ottileinchen** [clear-code/ieview-we#26]
Since the last Friefox and/or IEview WE update I get no IEview context menu item, and I cannot tick any check-box in the IEview WE options except "Save log". "Save log" is ticked, the rest is not (and looks disabled). I can change update, and I can enter text in "Path to ..." and in "Command line...". As I don't know where the log can be found, I cannot include it. I have a number of add-ons, but disbling all of them (except IEview, of course) did not help. I have this issue on at least two computers.
IEview 1.1.1 (companion app should be up-to-date), Firefox 59.0.2 (just updated - no change).

**Comment by kenhys** [comment]
Could you check whether you use latest native messaging host application with Ieview-we?

Reinstall this may help you.
https://github.com/clear-code/ieview-we/releases/download/v1.1.1/ieview-we-host.zip

**Comment by kenhys** [comment]
@Ottileinchen

 Is this issue reproducible even though IEView WE 1.2.0 and latest https://github.com/clear-code/ieview-we/releases/download/v1.2.0/ieview-we-host.zip ?

**Comment by Ottileinchen** [comment]
Not sure if you already got this:

Hi Kontaro,

no, it still does not work. I installed the host as admin and as user,
so I have it in
C:\Program Files\com.clear_code.ieview_we_host
and in
C:\Users\Otto\AppData\Local\com.clear_code.ieview_we_host
My Firefox Profiles folder is
D:\Otto\AppData\Mozilla\Firefox\Profiles
HOMEDRIVE is C:, and HOMEPATH is \Users\Otto, and the official AppData
is located there.

Let me know if I can help.

Best
Otto


On 13/04/2018 06:53, Kentaro Hayashi wrote:
> @Ottileinchen
>
>  Is this issue reproducible even though IEView WE 1.2.0 and latest
https://github.com/clear-code/ieview-we/releases/download/v1.2.0/ieview-we-host.zip
?
>

-- 
    //_            Dr. Otto PETER
  .00__
 /_     \ /
   \____/^         A-6020 Innsbruck, Österreich
    _/|_           Tel.: +43-512-507-52718
                   Email: otto.peter@uibk.ac.at

**Comment by kenhys** [comment]
@Ottileinchen  Could you help us to show webconsole messages for investigating such a behavior in details?

I mean:

1. Launch Firefox with `-jsconsole` option

```
"c:¥Program Files (x86)¥Mozilla Firefox¥firefox.exe" -jsconsole
```
2. In jsconsole window, right click and "Select all"
3. In jsconsole window, Ctrl + C to copy them.
4. Paste log messages in this issue

```
TODO: paste by Ctrl+V here
```

**Comment by morbeus7** [comment]
I have possibly the same issue but there is a difference which may mean I'll have to open a new issue.
I have Windows 7, Firefox 60.0.1 (64bit), I.E. 11.0.9600, and ieview-we 1.3.0
After an update of Firefox to 59,x,x I could no longer see the IEview context menu item.   At least that is what I thought until I noticed that there was a blank context menu item in the RMB popup menu.  Clicking on that blank item results in IE being started correctly with the correct URL.  So the only issue is that I cannot see the text.  Is the behavior I see possibly related to this GITHUB issue?

**Comment by mikhoul** [comment]
Here everything work fine with Win 8.1 + Firefox 60.0.1 **EXCEPT** the "_**Close blank tab left after redirection**_" that is grayed out so the option is not available for me.

![image](https://user-images.githubusercontent.com/5678673/40273024-949fd2be-5b86-11e8-8a4d-d846950845d2.png)

**Comment by terra111** [comment]
I have the same issue. 
-Windows 7, 64bit
-Installation of latest 1.3.0 ieview-we-host.zip runs as Administrator, no installation errors
-Firefox 60.0.2, 64bit runs as Administrator and installation of IE view WE 1.3.0, no installation errors

![ie view we 1 3 0 funktioniert nicht richtig](https://user-images.githubusercontent.com/38210654/41845882-8cf7f424-7864-11e8-9788-060279dd9ac8.png)



-jsconsole output as you asked for:

Error: Could not establish connection. Receiving end does not exist.  Configs.js:270:27

**Comment by Dimas-sc** [comment]
> "c:\Program Files (x86)\Mozilla Firefox\firefox.exe" -jsconsole

ieview-we: Sending:  {"command":"read-mcd-configs","logging":true,"logRotationCount":12,"logRotationTime":24}  common.js:14:40
ieview-we: loaded MCD configs:  {"disableForce":false,"closeReloadPage":false,"contextMenu":false,"onlyMainFrame":false,"disableException":false,"ignoreQueryString":false,"debug":false,"logs":["logRotationCount:12","logRotationTime:24h0m0s","Command is read-mcd-configs","Logs from mcd:\n  Got application path is c:\\Program Files\\Mozilla Firefox\\firefox.exe\n  No match for the pattern c:\\Program Files\\Mozilla Firefox\\*.cfg\n  Failed to get path to local config file.\n  No match for the pattern C:\\Users\\dimas\\AppData\\Roaming\\Mozilla\\Firefox\\Profiles\\*.default\\failover.jsc\n  No match for the pattern C:\\Users\\dimas\\AppData\\Roaming\\Mozilla\\Firefox\\Profiles\\*\\failover.jsc\n  Failed to get path to failover.jsc","Failed to read extensions.ieview.disableForce.\nunknown pref: extensions.ieview.disableForce","Failed to read extensions.ieview.closeReloadPage.\nunknown pref: extensions.ieview.closeReloadPage","Failed to read extensions.ieview.disableException.\nunknown pref: extensions.ieview.disableException","Failed to read extensions.ieview.contextMenu.\nunknown pref: extensions.ieview.contextMenu","Failed to read extensions.ieview.onlyMainFrame.\nunknown pref: extensions.ieview.onlyMainFrame","Failed to read extensions.ieview.ignoreQueryString.\nunknown pref: extensions.ieview.ignoreQueryString","Failed to read extensions.ieview.debug.\nunknown pref: extensions.ieview.debug"]}  common.js:14:40
ieview-we: force list:  Array [ "*ecap.intranet*ecap*", "*ecap.intranet*siap*" ]  common.js:14:40
ieview-we: convert host to regex: *://*.ecap.intranet*ecap/*  common.js:14:40
ieview-we: pattern is not a valid MatchPattern *://*.ecap.intranet*ecap/*  common.js:14:40
Error: Could not establish connection. Receiving end does not exist.  Configs.js:270:27
TypeError: "*://*.ecap.intranet*ecap/*" is not a valid MatchPattern  background.js:157:11
Error: Could not establish connection. Receiving end does not exist.  Configs.js:270:27

**Comment by Dimas-sc** [comment]
I tried this addon but is not working for me. ESR 60, latest IE View WE 1.3.0. After the fresh install I could put some URLs in the force filter but after restarting Firefox:

- The settings/checkboxes are disabled. 
- about:config don't contain any ieview pref. I don't have any Autoconfig/MCD configuration.
- C:\Users\{user}\AppData\Local\Temp\com.clear_code.ieview_we.log.201902260100 doesn't update with any error/warnings.
- C:\Users\{user}\AppData\Roaming\Mozilla\Firefox\Profiles\{id}.default\browser-extension-data\ieview-we@clear-code.com\storage.js contains:
`{"forceielist":"*ecap.intranet*ecap*\n*ecap.intranet*siap*","disableForce":false,"closeReloadPage":false,"contextMenu":false,"onlyMainFrame":false,"disableException":false,"ignoreQueryString":false,"debug":false,"logs":["logRotationCount:12","logRotationTime:24h0m0s","Command is read-mcd-configs","Logs from mcd:\n  Got application path is c:\\Program Files\\Mozilla Firefox\\firefox.exe\n  No match for the pattern c:\\Program Files\\Mozilla Firefox\\*.cfg\n  Failed to get path to local config file.\n  No match for the pattern C:\\Users\\dimas\\AppData\\Roaming\\Mozilla\\Firefox\\Profiles\\*.default\\failover.jsc\n  No match for the pattern C:\\Users\\dimas\\AppData\\Roaming\\Mozilla\\Firefox\\Profiles\\*\\failover.jsc\n  Failed to get path to failover.jsc","Failed to read extensions.ieview.disableForce.\nunknown pref: extensions.ieview.disableForce","Failed to read extensions.ieview.closeReloadPage.\nunknown pref: extensions.ieview.closeReloadPage","Failed to read extensions.ieview.disableException.\nunknown pref: extensions.ieview.disableException","Failed to read extensions.ieview.contextMenu.\nunknown pref: extensions.ieview.contextMenu","Failed to read extensions.ieview.onlyMainFrame.\nunknown pref: extensions.ieview.onlyMainFrame","Failed to read extensions.ieview.ignoreQueryString.\nunknown pref: extensions.ieview.ignoreQueryString","Failed to read extensions.ieview.debug.\nunknown pref: extensions.ieview.debug"],"ieapp":"C:\\Program Files\\Internet Explorer\\IEXPLORE.EXE","logging":true}`

**Comment by piroor** [comment]
954a0e7 should fix this.
