### ISSUE TITLE
You should consider to port it to Chrome/Chromium

### ISSUE THREAD

**Issue by mikhoul** [clear-code/ieview-we#27]
I really like this addon since I use both Firefox and Chromium I'd really like if you could port it to Chromium too. Where I live there is lot of Government websites that use ActiveX/Silverlight Technologies and for those site this extension is very useful. 

Also I don't care if  you would not put your extension in the Chrome Store since I would load it unpackaged in Dev mode.

Thanks again for this little gem :octocat:

**Comment by mikhoul** [comment]
@clear-code  I forget in my previous message to let you know if you port it to Chrome and want to make your life easier you could use one of the numerous polyfil like  https://github.com/mozilla/webextension-polyfill or https://github.com/taylorhakes/promise-polyfill 

This way you will use 98% the same code for both Firefox and Chromium :wink:

**Comment by piroor** [comment]
Now it is available at https://chrome.google.com/webstore/detail/ie-view-we/nifnmbbelnhfhgeiampkfghakhmgggcf ! Please note that you need to use the native messaging host v1.5.3 or later for Chrome. https://github.com/clear-code/ieview-we/releases/tag/v1.5.3
