### ISSUE TITLE
Small bug: Close blank tab  is greyed out and not availlable

### ISSUE THREAD

**Issue by mikhoul** [clear-code/ieview-we#28]
I'm not able to tick the box to enable the option.

![image](https://user-images.githubusercontent.com/5678673/40262656-0a5bfdf8-5ad7-11e8-800a-6d1b10dd3f4a.png)

 I'have seen your latest commit is about this option so maybe the new version is waiting for approval in AMO. I use Version 1.3.0

Regards :octocat:

**Comment by jerlev-p** [comment]
Having same issue, except that ALL checkboxes are disabled!!

![image](https://user-images.githubusercontent.com/16012615/47297490-321f3a80-d5e3-11e8-8bd2-fd6ea192033c.png)

**Comment by piroor** [comment]
When you use a MCD configuration file (`*.cfg` at the folder same to `firefox.exe`) or installed the managed storage file, IE View WE locks UIs for options loaded from these files. Have you tried them?

**Comment by Dimas-sc** [comment]
See #26 , I think it's related. The addon auto-creates C:\Users{user}\AppData\Roaming\Mozilla\Firefox\Profiles{id}.default\browser-extension-data\ieview-we@clear-code.com\storage.js and I think this file is locking the preferences.

**Comment by piroor** [comment]
Ah, OK, I got it. This is a regression of 40ff4d2345106a84e736c9933a07a42b8b1dd1fc. After this change, the native messaging host returns boolean options as `false` even if they are not defined, and the WebExtensions side detects those configs as `locked with false value`. The native messaging host must return something extra information to indicate which values are actually loaded.

**Comment by piroor** [comment]
954a0e7 should fix this.
