### ISSUE TITLE
IE View WE does not redirect from Firefox to IE on 64 bit OS versions ( Win 7 and Win 10 )

### ISSUE THREAD

**Issue by Admitr** [clear-code/ieview-we#32]
IE View WE does not redirect from Firefox to IE on 64 bit OS versions ( Win 7 and Win 10 )
The extension is configured, showing as installed and enabled, the list of URLs set to be redirected is in place. When I attempt to test one of the listed URLs and have it redirected from FF to IE - nothing happens on 64 bit OS versions of Windows 7 and Windows 10. On the other hand same setup on Windows 7 32 bit it works perfectly fine.
Is there anything that is missing for 64 bit ? any additional configurations / settings to be done ?
Please advise.

**Comment by Dimas-sc** [comment]
I've tested it on Windows 7 and Windows 10, both 64 bits with Firefox 68.2 ESR and it works ok for me.

**Comment by piroor** [comment]
We've released the native messaging host v1.5.3: https://github.com/clear-code/ieview-we/releases/tag/v1.5.3 Could you try that?

**Comment by piroor** [comment]
I close this for now as expired.
