### ISSUE TITLE
Request: Wrap URL in quotes for third-party app

### ISSUE THREAD

**Issue by ConorIA** [clear-code/ieview-we#33]
Hello, 

I was being driven mad by each redirect opening a new IE window. I have come up with a hacky workaround by replacing the following values: 

Path to Internet Explorer: _powershell.exe_
Command Line Arguments: _C:\path\to\storage\open_in_ie.ps1_

The content of _open_in_ie.ps1_ looks like this: 

```powershell
$url = $Args[0]

$is_running = Get-Process iexplore -ErrorAction SilentlyContinue
if (!$is_running) {
  & "C:\Program Files\Internet Explorer\iexplore.exe" $url
  exit 
}
Remove-Variable is_running

$navOpenInNewTab = 0x800

# Get running Internet Explorer instances
$App = New-Object -ComObject shell.application

# Grab the last opened tab
$IE = $App.Windows() | Select-Object -Last 1

# Open link in the new tab nearby
$IE.navigate($url, $navOpenInNewTab)

# Cleanup
'App', 'IE' | ForEach-Object {Remove-Variable $_ -Force}
```

_[source](https://superuser.com/a/877249) for most of above_

My problem is that the workaround does not work for URLs with Amperands: 

```
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass 
it as part of a string.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : AmpersandNotAllowed
```

I am not sure exactly where the extension passes the URL to "Internet Explorer" (powershell in my case).  I am assuming that it is in the host app. Is it possible to have the URL passed as a string? i.e. wrap the URL in double quotes?

Alternatively, is there a way to ensure that new tabs open in an existing IE window?

**Comment by piroor** [comment]
Sorry for this 1 year delay...

Thank you for this report and the PR! After reviewing I realized that URL with quotations doesn't work with Internet Explorer 11 on my environment. So, I've introduced a change instead:

* You can put `%s` or `%**` as a placeholder in the arguments list. This is already available on v1.5.2 and older versions.
* On v1.5.3 native messaging host (I've released it today), you can put the placeholder in quotations like `"%s"`. If your scripts requires a URL argument as a quoted string, please put it into the options field in the IE View WE's options page.

**Comment by piroor** [comment]
The updated native messaging host is downloadable at: https://github.com/clear-code/ieview-we/releases/tag/v1.5.3

**Comment by ConorIA** [comment]
Seems to be working great! Thanks very much.
