### ISSUE TITLE
ieview-we-host.zip is missing

### ISSUE THREAD

**Issue by ajkessel** [clear-code/ieview-we#37]
The plugin instructions tell the user to find "ieview-we-host.zip" on Github--but there is no file with that name on the site (at least that I could find). Is the only option building from source? Instructions should be clarified if so.

**Comment by fujimotos** [comment]
You can install the host program from here:

https://github.com/clear-code/ieview-we/releases/tag/v1.5.1

**Comment by ajkessel** [comment]
Thanks! Is there a reason it's not listed with the latest release? Perhaps there should be a permanent URL for the current version to make it easier to find from the addon readme file?

**Comment by fujimotos** [comment]
> Is there a reason it's not listed with the latest release?

@ajkessel No reason. it is just not modified since v1.3.0, so we just did
not bother to upload to the release page (since it's all the same with
the previous version).

We'll gonna make the latest link page more obvious to users.
