### ISSUE TITLE
Report native messaging host version on EXE

### ISSUE THREAD

**Issue by Dimas-sc** [clear-code/ieview-we#38]
We distribute the Firefox extensions via policies, and in ieview-we case we also distribute the native messaging host via batch scripts. Now that it was updated to the 1.5.3 version I don't know how to detect old installations to update it. Is it possible to report the host version in the exe details? Now if I look at the exe version is null. Thx.

**Comment by Dimas-sc** [comment]
Can I ask you a question? What happens if the extension is updated to 1.5.3 but host stays in a old version? And if the extensions is the old 1.5.2 and the native host is updated to the new 1.5.3?
Thx

**Comment by piroor** [comment]
Sorry for this delay. I've added a command line option "-v" to output the version number, so it will help you to detect the installed version of the native messaging host.

Changes in the native messaging host between 1.5.2 and 1.5.3 are:

* Add support for Google Chrome. (You can use the native messaging host from the IE View WE extension for Chrome.)
* Add support for logging with STDERR.
* Add support for the placeholder `%s` and `%**` in the command line options for the helper application. It will be replaced to a URL safely.

**Comment by Dimas-sc** [comment]
I try to execute "host -v" or "host.exe -v" etc... but it don't output nothing :-(
